### ISSUE TITLE
For next iteration of the course (June 2023) , add this piece of code into the script day1_code.R

### ISSUE THREAD

**Issue by dianamarek** [sib-swiss/first-steps-with-R-training#2]
add this piece of code into the script day1_code.R

# change  class of these three vectors to factor
snps$chr <-factor(snps$chr)
snps$minor <-factor(snps$minor)
snps$major <-factor(snps$major)

it should go after the summary( snps ) command

**Comment by WandrilleD** [comment]
code added to the files. Thanks.
