### ISSUE TITLE
Identical solution files? 

### ISSUE THREAD

**Issue by dianamarek** [sib-swiss/first-steps-with-R-training#5]
Hi, 
Is there any difference between file R_practice10_solution.R and R_practice11_solution.R. They look identical.
If it is the case,  i can delete the practice11.  Let me know.
Diana

**Comment by WandrilleD** [comment]
Indeed, the let's practice shifted number and 11 does not exists anymore.
This solution file should be removed

**Comment by dianamarek** [comment]
Ok great, just deleted the file and committed the change to the master. Closing the issue now.
